/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalStatementRouteImport } from './routes/portal.statement'
import { Route as PortalNewCaseRouteImport } from './routes/portal.new-case'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalCasesRouteImport } from './routes/portal.cases'
import { Route as ApiPortalResolveLoginRouteImport } from './routes/api/portal-resolve-login'
import { Route as ApiManageUserRouteImport } from './routes/api/manage-user'
import { Route as ApiCreateDoctorAccountRouteImport } from './routes/api/create-doctor-account'
import { Route as ApiAiPredictDeliveryRouteImport } from './routes/api/ai-predict-delivery'
import { Route as ApiAiDailyInsightsRouteImport } from './routes/api/ai-daily-insights'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as ApiAiAnalyzeCaseRouteImport } from './routes/api/ai-analyze-case'
import { Route as AppWorkflowsRouteImport } from './routes/_app.workflows'
import { Route as AppVouchersRouteImport } from './routes/_app.vouchers'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTechniciansRouteImport } from './routes/_app.technicians'
import { Route as AppTechnicianReportsRouteImport } from './routes/_app.technician-reports'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppStatementsRouteImport } from './routes/_app.statements'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppPricingRouteImport } from './routes/_app.pricing'
import { Route as AppPendingCasesRouteImport } from './routes/_app.pending-cases'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDoctorsRouteImport } from './routes/_app.doctors'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCashAccountsRouteImport } from './routes/_app.cash-accounts'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppBackupRouteImport } from './routes/_app.backup'
import { Route as AppCasesNewRouteImport } from './routes/_app.cases.new'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app.cases.$caseId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalStatementRoute = PortalStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNewCaseRoute = PortalNewCaseRouteImport.update({
  id: '/new-case',
  path: '/new-case',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCasesRoute = PortalCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => PortalRoute,
} as any)
const ApiPortalResolveLoginRoute = ApiPortalResolveLoginRouteImport.update({
  id: '/api/portal-resolve-login',
  path: '/api/portal-resolve-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManageUserRoute = ApiManageUserRouteImport.update({
  id: '/api/manage-user',
  path: '/api/manage-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateDoctorAccountRoute = ApiCreateDoctorAccountRouteImport.update({
  id: '/api/create-doctor-account',
  path: '/api/create-doctor-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPredictDeliveryRoute = ApiAiPredictDeliveryRouteImport.update({
  id: '/api/ai-predict-delivery',
  path: '/api/ai-predict-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDailyInsightsRoute = ApiAiDailyInsightsRouteImport.update({
  id: '/api/ai-daily-insights',
  path: '/api/ai-daily-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAnalyzeCaseRoute = ApiAiAnalyzeCaseRouteImport.update({
  id: '/api/ai-analyze-case',
  path: '/api/ai-analyze-case',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppVouchersRoute = AppVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTechniciansRoute = AppTechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => AppRoute,
} as any)
const AppTechnicianReportsRoute = AppTechnicianReportsRouteImport.update({
  id: '/technician-reports',
  path: '/technician-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingCasesRoute = AppPendingCasesRouteImport.update({
  id: '/pending-cases',
  path: '/pending-cases',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCashAccountsRoute = AppCashAccountsRouteImport.update({
  id: '/cash-accounts',
  path: '/cash-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesNewRoute = AppCasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AppCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/backup': typeof AppBackupRoute
  '/cases': typeof AppCasesRouteWithChildren
  '/cash-accounts': typeof AppCashAccountsRoute
  '/dashboard': typeof AppDashboardRoute
  '/doctors': typeof AppDoctorsRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRoute
  '/messages': typeof AppMessagesRoute
  '/patients': typeof AppPatientsRoute
  '/pending-cases': typeof AppPendingCasesRoute
  '/pricing': typeof AppPricingRoute
  '/purchases': typeof AppPurchasesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/statements': typeof AppStatementsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/technician-reports': typeof AppTechnicianReportsRoute
  '/technicians': typeof AppTechniciansRoute
  '/users': typeof AppUsersRoute
  '/vouchers': typeof AppVouchersRoute
  '/workflows': typeof AppWorkflowsRoute
  '/api/ai-analyze-case': typeof ApiAiAnalyzeCaseRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-daily-insights': typeof ApiAiDailyInsightsRoute
  '/api/ai-predict-delivery': typeof ApiAiPredictDeliveryRoute
  '/api/create-doctor-account': typeof ApiCreateDoctorAccountRoute
  '/api/manage-user': typeof ApiManageUserRoute
  '/api/portal-resolve-login': typeof ApiPortalResolveLoginRoute
  '/portal/cases': typeof PortalCasesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/new-case': typeof PortalNewCaseRoute
  '/portal/statement': typeof PortalStatementRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/cases/new': typeof AppCasesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/backup': typeof AppBackupRoute
  '/cases': typeof AppCasesRouteWithChildren
  '/cash-accounts': typeof AppCashAccountsRoute
  '/dashboard': typeof AppDashboardRoute
  '/doctors': typeof AppDoctorsRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRoute
  '/messages': typeof AppMessagesRoute
  '/patients': typeof AppPatientsRoute
  '/pending-cases': typeof AppPendingCasesRoute
  '/pricing': typeof AppPricingRoute
  '/purchases': typeof AppPurchasesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/statements': typeof AppStatementsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/technician-reports': typeof AppTechnicianReportsRoute
  '/technicians': typeof AppTechniciansRoute
  '/users': typeof AppUsersRoute
  '/vouchers': typeof AppVouchersRoute
  '/workflows': typeof AppWorkflowsRoute
  '/api/ai-analyze-case': typeof ApiAiAnalyzeCaseRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-daily-insights': typeof ApiAiDailyInsightsRoute
  '/api/ai-predict-delivery': typeof ApiAiPredictDeliveryRoute
  '/api/create-doctor-account': typeof ApiCreateDoctorAccountRoute
  '/api/manage-user': typeof ApiManageUserRoute
  '/api/portal-resolve-login': typeof ApiPortalResolveLoginRoute
  '/portal/cases': typeof PortalCasesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/new-case': typeof PortalNewCaseRoute
  '/portal/statement': typeof PortalStatementRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/cases/new': typeof AppCasesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/_app/backup': typeof AppBackupRoute
  '/_app/cases': typeof AppCasesRouteWithChildren
  '/_app/cash-accounts': typeof AppCashAccountsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/doctors': typeof AppDoctorsRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/pending-cases': typeof AppPendingCasesRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/statements': typeof AppStatementsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/technician-reports': typeof AppTechnicianReportsRoute
  '/_app/technicians': typeof AppTechniciansRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/vouchers': typeof AppVouchersRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/api/ai-analyze-case': typeof ApiAiAnalyzeCaseRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-daily-insights': typeof ApiAiDailyInsightsRoute
  '/api/ai-predict-delivery': typeof ApiAiPredictDeliveryRoute
  '/api/create-doctor-account': typeof ApiCreateDoctorAccountRoute
  '/api/manage-user': typeof ApiManageUserRoute
  '/api/portal-resolve-login': typeof ApiPortalResolveLoginRoute
  '/portal/cases': typeof PortalCasesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/new-case': typeof PortalNewCaseRoute
  '/portal/statement': typeof PortalStatementRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/_app/cases/new': typeof AppCasesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/signup'
    | '/backup'
    | '/cases'
    | '/cash-accounts'
    | '/dashboard'
    | '/doctors'
    | '/expenses'
    | '/inventory'
    | '/invoices'
    | '/messages'
    | '/patients'
    | '/pending-cases'
    | '/pricing'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/statements'
    | '/suppliers'
    | '/technician-reports'
    | '/technicians'
    | '/users'
    | '/vouchers'
    | '/workflows'
    | '/api/ai-analyze-case'
    | '/api/ai-chat'
    | '/api/ai-daily-insights'
    | '/api/ai-predict-delivery'
    | '/api/create-doctor-account'
    | '/api/manage-user'
    | '/api/portal-resolve-login'
    | '/portal/cases'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/new-case'
    | '/portal/statement'
    | '/cases/$caseId'
    | '/cases/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/signup'
    | '/backup'
    | '/cases'
    | '/cash-accounts'
    | '/dashboard'
    | '/doctors'
    | '/expenses'
    | '/inventory'
    | '/invoices'
    | '/messages'
    | '/patients'
    | '/pending-cases'
    | '/pricing'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/statements'
    | '/suppliers'
    | '/technician-reports'
    | '/technicians'
    | '/users'
    | '/vouchers'
    | '/workflows'
    | '/api/ai-analyze-case'
    | '/api/ai-chat'
    | '/api/ai-daily-insights'
    | '/api/ai-predict-delivery'
    | '/api/create-doctor-account'
    | '/api/manage-user'
    | '/api/portal-resolve-login'
    | '/portal/cases'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/new-case'
    | '/portal/statement'
    | '/cases/$caseId'
    | '/cases/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/portal'
    | '/signup'
    | '/_app/backup'
    | '/_app/cases'
    | '/_app/cash-accounts'
    | '/_app/dashboard'
    | '/_app/doctors'
    | '/_app/expenses'
    | '/_app/inventory'
    | '/_app/invoices'
    | '/_app/messages'
    | '/_app/patients'
    | '/_app/pending-cases'
    | '/_app/pricing'
    | '/_app/purchases'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/statements'
    | '/_app/suppliers'
    | '/_app/technician-reports'
    | '/_app/technicians'
    | '/_app/users'
    | '/_app/vouchers'
    | '/_app/workflows'
    | '/api/ai-analyze-case'
    | '/api/ai-chat'
    | '/api/ai-daily-insights'
    | '/api/ai-predict-delivery'
    | '/api/create-doctor-account'
    | '/api/manage-user'
    | '/api/portal-resolve-login'
    | '/portal/cases'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/new-case'
    | '/portal/statement'
    | '/_app/cases/$caseId'
    | '/_app/cases/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  SignupRoute: typeof SignupRoute
  ApiAiAnalyzeCaseRoute: typeof ApiAiAnalyzeCaseRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiDailyInsightsRoute: typeof ApiAiDailyInsightsRoute
  ApiAiPredictDeliveryRoute: typeof ApiAiPredictDeliveryRoute
  ApiCreateDoctorAccountRoute: typeof ApiCreateDoctorAccountRoute
  ApiManageUserRoute: typeof ApiManageUserRoute
  ApiPortalResolveLoginRoute: typeof ApiPortalResolveLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/statement': {
      id: '/portal/statement'
      path: '/statement'
      fullPath: '/portal/statement'
      preLoaderRoute: typeof PortalStatementRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/new-case': {
      id: '/portal/new-case'
      path: '/new-case'
      fullPath: '/portal/new-case'
      preLoaderRoute: typeof PortalNewCaseRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/cases': {
      id: '/portal/cases'
      path: '/cases'
      fullPath: '/portal/cases'
      preLoaderRoute: typeof PortalCasesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/portal-resolve-login': {
      id: '/api/portal-resolve-login'
      path: '/api/portal-resolve-login'
      fullPath: '/api/portal-resolve-login'
      preLoaderRoute: typeof ApiPortalResolveLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manage-user': {
      id: '/api/manage-user'
      path: '/api/manage-user'
      fullPath: '/api/manage-user'
      preLoaderRoute: typeof ApiManageUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-doctor-account': {
      id: '/api/create-doctor-account'
      path: '/api/create-doctor-account'
      fullPath: '/api/create-doctor-account'
      preLoaderRoute: typeof ApiCreateDoctorAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-predict-delivery': {
      id: '/api/ai-predict-delivery'
      path: '/api/ai-predict-delivery'
      fullPath: '/api/ai-predict-delivery'
      preLoaderRoute: typeof ApiAiPredictDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-daily-insights': {
      id: '/api/ai-daily-insights'
      path: '/api/ai-daily-insights'
      fullPath: '/api/ai-daily-insights'
      preLoaderRoute: typeof ApiAiDailyInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-analyze-case': {
      id: '/api/ai-analyze-case'
      path: '/api/ai-analyze-case'
      fullPath: '/api/ai-analyze-case'
      preLoaderRoute: typeof ApiAiAnalyzeCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vouchers': {
      id: '/_app/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AppVouchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/technicians': {
      id: '/_app/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof AppTechniciansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/technician-reports': {
      id: '/_app/technician-reports'
      path: '/technician-reports'
      fullPath: '/technician-reports'
      preLoaderRoute: typeof AppTechnicianReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statements': {
      id: '/_app/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pending-cases': {
      id: '/_app/pending-cases'
      path: '/pending-cases'
      fullPath: '/pending-cases'
      preLoaderRoute: typeof AppPendingCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctors': {
      id: '/_app/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-accounts': {
      id: '/_app/cash-accounts'
      path: '/cash-accounts'
      fullPath: '/cash-accounts'
      preLoaderRoute: typeof AppCashAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backup': {
      id: '/_app/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/new': {
      id: '/_app/cases/new'
      path: '/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof AppCasesNewRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppCasesRoute
    }
  }
}

interface AppCasesRouteChildren {
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppCasesNewRoute: typeof AppCasesNewRoute
}

const AppCasesRouteChildren: AppCasesRouteChildren = {
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppCasesNewRoute: AppCasesNewRoute,
}

const AppCasesRouteWithChildren = AppCasesRoute._addFileChildren(
  AppCasesRouteChildren,
)

interface AppRouteChildren {
  AppBackupRoute: typeof AppBackupRoute
  AppCasesRoute: typeof AppCasesRouteWithChildren
  AppCashAccountsRoute: typeof AppCashAccountsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDoctorsRoute: typeof AppDoctorsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPendingCasesRoute: typeof AppPendingCasesRoute
  AppPricingRoute: typeof AppPricingRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTechnicianReportsRoute: typeof AppTechnicianReportsRoute
  AppTechniciansRoute: typeof AppTechniciansRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVouchersRoute: typeof AppVouchersRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBackupRoute: AppBackupRoute,
  AppCasesRoute: AppCasesRouteWithChildren,
  AppCashAccountsRoute: AppCashAccountsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDoctorsRoute: AppDoctorsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPendingCasesRoute: AppPendingCasesRoute,
  AppPricingRoute: AppPricingRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTechnicianReportsRoute: AppTechnicianReportsRoute,
  AppTechniciansRoute: AppTechniciansRoute,
  AppUsersRoute: AppUsersRoute,
  AppVouchersRoute: AppVouchersRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalCasesRoute: typeof PortalCasesRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalNewCaseRoute: typeof PortalNewCaseRoute
  PortalStatementRoute: typeof PortalStatementRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCasesRoute: PortalCasesRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalNewCaseRoute: PortalNewCaseRoute,
  PortalStatementRoute: PortalStatementRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  SignupRoute: SignupRoute,
  ApiAiAnalyzeCaseRoute: ApiAiAnalyzeCaseRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiDailyInsightsRoute: ApiAiDailyInsightsRoute,
  ApiAiPredictDeliveryRoute: ApiAiPredictDeliveryRoute,
  ApiCreateDoctorAccountRoute: ApiCreateDoctorAccountRoute,
  ApiManageUserRoute: ApiManageUserRoute,
  ApiPortalResolveLoginRoute: ApiPortalResolveLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
